services:
  db:
    image: postgres:16
    container_name: movies-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviesdb
    ports: ["5432:5432"]
    volumes: [ "db_data:/var/lib/postgresql/data" ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d moviesdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  web:
    build:
      context: .          # ТЕКУЩАЯ папка Asp/
      dockerfile: Dockerfile
    container_name: movies-web
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__MovieDbCS: "Host=db;Port=5432;Database=moviesdb;Username=postgres;Password=postgres"
    ports: ["8080:8080"]

volumes:
  db_data: {}
